# SPDX-License-Identifier: AGPL-3.0-or-later
"""The only sanctioned way to read an asset or a folder: the permission rule is compiled into the
one statement, so a page and its count always agree."""

from __future__ import annotations

from sift.kernel.access.repository.assets import (
    ADMIN_FACETS,
    DEFAULT_SORT,
    FACET_LABELS,
    FACETS,
    FACETS_RENAMED,
    RELEVANCE,
    SEEKABLE_SORTS,
    SHUFFLE_MODULUS,
    SIMILARITY,
    SORT_KEYS,
)
from sift.kernel.access.repository.entities import (
    ENTITY_SORT_KEYS,
    ENTITY_SORT_SEEN,
    SONG_SORT_KEYS,
)
from sift.kernel.access.repository.store import (
    MAX_PAGE_SIZE,
    Named,
    Recording,
    Repository,
)
from sift.kernel.access.repository.views import (
    AccessError,
    Actionable,
    AliasMatch,
    AssetPage,
    AssetView,
    CollectionPage,
    CollectionView,
    Enrichment,
    FacetCount,
    Folder,
    FolderContents,
    Grant,
    GrantMark,
    GrantSource,
    LoopPage,
    LoopTag,
    LoopView,
    Memberships,
    PeoplePage,
    PersonSuggestion,
    PhotoSetPage,
    PhotoSetView,
    Reaches,
    ServedDerivative,
    SitePage,
    SiteSuggestion,
    SongPage,
    SongView,
    TagPage,
    TagSuggestion,
    UsernamePage,
    UsernameSuggestion,
    VaultSource,
)
from sift.kernel.access.viewer import ConcealerType

__all__ = [
    "ADMIN_FACETS",
    "DEFAULT_SORT",
    "ENTITY_SORT_KEYS",
    "ENTITY_SORT_SEEN",
    "FACETS",
    "FACETS_RENAMED",
    "FACET_LABELS",
    "MAX_PAGE_SIZE",
    "RELEVANCE",
    "SEEKABLE_SORTS",
    "SHUFFLE_MODULUS",
    "SIMILARITY",
    "SONG_SORT_KEYS",
    "SORT_KEYS",
    "AccessError",
    "Actionable",
    "AliasMatch",
    "AssetPage",
    "AssetView",
    "CollectionPage",
    "CollectionView",
    "ConcealerType",
    "Enrichment",
    "FacetCount",
    "Folder",
    "FolderContents",
    "Grant",
    "GrantMark",
    "GrantSource",
    "LoopPage",
    "LoopTag",
    "LoopView",
    "Memberships",
    "Named",
    "PeoplePage",
    "PersonSuggestion",
    "PhotoSetPage",
    "PhotoSetView",
    "Reaches",
    "Recording",
    "Repository",
    "ServedDerivative",
    "SitePage",
    "SiteSuggestion",
    "SongPage",
    "SongView",
    "TagPage",
    "TagSuggestion",
    "UsernamePage",
    "UsernameSuggestion",
    "VaultSource",
]
