# SPDX-License-Identifier: AGPL-3.0-or-later
"""Every sentence a history says, built as PIECES, and the address each thing it names lives at.

## One sentence per act, on every screen

One act must not be said four ways ("Sift named X here" on the file, "Linked image.png to X" in
the Settings feed, something else again on a decision's card), and a browser building its own
wording from a word table of its own drifts from the server's. So there is one builder per act,
here, and every screen is handed what it builds: a file's thread,
a person's, a tag's, a Site's, a Collection's and a Photo Set's, the Settings feed and Recent
decisions. The ONLY thing a screen changes is the VANTAGE: what the thing whose page this is gets
called in its own line: "this file", "them", "it", or, in the feed, which has no page, its name.

## Pieces, not a string and a list of names to search it for

A line is a tuple of `Piece`s: plain words, and words that stand for a thing (a person, a file, a
tag, a count of files) carrying the kind, the id and where pressing it goes. Each builder places
each thing where it sits, so nothing downstream ever looks for a name inside the words: a search
that would link every "d" in "Added to d" to a Collection called `d`. The browser draws the pieces
and builds nothing.

## The bar

Short, simple sentences: specific, plain and clear. And three rules:

  * THE ACTOR FIRST, ACTIVE VOICE: "You added ...", "Sift filed ...", "StashDB filled in ...". No
    name sits beside the time, because the line says who. Where the record names
    nobody (a table that stores what was decided and not who decided it), the line is passive
    and says so, rather than guessing "You" on an install with a second user.
  * ONE WORD PER ACT (the History word table): recognized; "Removed ... from"; Unhid; "Turned off /
    on stash-box lookups"; Kept private from; Discarded; Undone; Generated; "Indexed for Smart
    Search"; task; ID.
  * NO DASH BOLTING A SECOND FACT ONTO A LINE. Not "Asked StashDB", a dash, "nothing matched": the
    second fact is said in the sentence ("Sift asked StashDB and nothing matched").

## Why the addresses are written HERE, on the server

A link's `href` is a screen in the client, and this module is the one place that knows them. They
are the SAME addresses the filter bar writes when somebody clicks a facet row (a person's files
are `?people=<name>`, a folder is `?in=<path>`), so a history line and a click land on one list,
and a fault in the facet grammar is fixed there for both.
"""

from __future__ import annotations

from sift.kernel.access.sentences_downloads import (
    A_FILE,
    A_SITE,
    DOWNLOAD_SAID,
    FAILED_BECAUSE,
    KIND_BEFORE,
    STALE_FAILURES,
    download_failed,
    download_line,
    downloads_folded,
    failed_because,
    failure_today,
)
from sift.kernel.access.sentences_edited import (
    _edited_line,
    _took,
    _value_said,
    fields_of,
    number_changed,
    passes_of,
    setting_changed,
)
from sift.kernel.access.sentences_feed import (
    FEED,
    MACHINE_ACTS,
    TASK_TAIL,
    Act,
    _template,
    machine_line,
    payload_of,
)
from sift.kernel.access.sentences_file import (
    COPY_VERBS,
    CREATED,
    MATCH_GRADES,
    RENAMED_BECAUSE,
    RENAMED_FOR_TOOL_ID,
    UNDONE,
    Refusals,
    added,
    agreed_to_be,
    asked_and_found_nothing,
    asked_and_waiting,
    carried_sentence,
    copied_from,
    copied_into,
    copy_verb,
    filed_sentence,
    folder_of,
    how_sure,
    looked_for_faces,
    matched_sentence,
    moved,
    moved_into,
    named_sentence,
    open_on,
    recognized,
    recognized_face,
    refused_as,
    renamed,
    shared_with,
    tagged_sentence,
    undone,
)
from sift.kernel.access.sentences_folded import (
    TASK_TAIL_MANY,
    _grouped,
    feed_folded,
    subject_line_of,
)
from sift.kernel.access.sentences_gone import (
    DELETED_FROM,
    DELETED_ON,
    DELETED_WHY,
    MOST_ON,
    deleted_here,
    deleted_on,
    deleted_where,
)
from sift.kernel.access.sentences_ledger import (
    A_GONE,
    A_THING,
    BROUGHT_OVER,
    COVER_OBJECTS,
    COVER_WITHOUT_OBJECT,
    DELETED_KINDS,
    ENDS_ITS_THING,
    FIELD_WORDS,
    LINKED_KINDS,
    MERGE_NAMES_KEPT,
    MOST_FIELDS,
    FilledField,
    Group,
    Said,
    _filled_in,
    _filled_words,
    brought_named,
    brought_over,
    cover_changed,
    edited_fields,
    edited_folded,
    filled_field,
    filled_fields,
    filled_in_fold,
    mention,
    name_of,
    since_deleted,
    since_removed,
)
from sift.kernel.access.sentences_lines import RECORDED_NOTHING, event_said, feed_line
from sift.kernel.access.sentences_means import MEANS, means
from sift.kernel.access.sentences_people import (
    box_filled_named,
    box_line,
    entity_added,
    entity_created,
    faces_agreed,
    faces_refused,
    filed_under,
    filled_folded,
    linked_before_recorded,
    members_added,
    named_on,
    person_added,
    put_on,
    ruled_out_of,
    song_named_here,
    taught_by,
    usernames_added,
)
from sift.kernel.access.sentences_pieces import (
    A_STASH_BOX,
    ANOTHER_USER,
    FACES_CONFIRMED,
    FACES_MATCHED,
    FACES_WAITING,
    FEED_MOST,
    HERE,
    SIFT,
    THE_TOP,
    VANTAGE_ENTITY,
    VANTAGE_FILE,
    VANTAGE_PERSON,
    WHOSE,
    YOU,
    Line,
    Part,
    Piece,
    and_then,
    capitalized,
    counted_faces,
    counted_line,
    download_row,
    faces,
    faces_of_person,
    files,
    files_in_folder,
    files_of_username,
    folder_named,
    listed,
    many,
    may_be_faces,
    people,
    plural,
    said,
    tags,
    text_of,
    thing,
    things_in,
    times,
    username_opens,
    usernames,
)
from sift.kernel.access.sentences_songs import (
    SONG_FROM_ACOUSTID,
    SONG_FROM_SAME_MUSIC,
    SONG_FROM_SWAP,
    _song_line,
    as_then,
    boxes_recorded,
    departures_kept,
    merged_line,
    songs_moved,
)
from sift.kernel.access.sentences_sources import (
    ACOUSTID_SAID,
    ACOUSTID_SAID_PRESSED,
    COULD_NOT,
    MADE_READY,
    acoustid_answered,
    could_not,
    details_read_again,
    downloaded,
    faces_set_aside,
    faces_taken_off,
    fingerprinted_by,
    hidden_here,
    kept_mine,
    made_ready,
    music_fingerprinted,
    nothing_to_fingerprint,
    person_refused,
    processed,
    processed_steps,
    read_its_meaning,
    watermark_found,
    watermark_none,
    watermark_refused,
)
from sift.kernel.access.sentences_swaps import (
    BY_HAND,
    PICTURE_ALONE,
    SWAP,
    SWAP_ENDED,
    TOOK_BACK,
    added_by,
    swap_ended,
    swap_started,
    took_back_said,
)
from sift.kernel.access.sentences_who import (
    ANSWER_OF,
    FROM_ACT,
    FROM_PASS,
    FROM_PASS_MANY,
    PRESSED_ACTS,
    SIFT_FROM,
    STALE_IN_A_TITLE,
    by_word,
    from_maker,
    from_pass,
    had_sift,
    pressed_act,
    pressed_here,
    sift_from,
    times_said,
    today_words,
)

__all__ = [
    "ACOUSTID_SAID",
    "ACOUSTID_SAID_PRESSED",
    "ANOTHER_USER",
    "ANSWER_OF",
    "A_FILE",
    "A_GONE",
    "A_SITE",
    "A_STASH_BOX",
    "A_THING",
    "BROUGHT_OVER",
    "BY_HAND",
    "COPY_VERBS",
    "COULD_NOT",
    "COVER_OBJECTS",
    "COVER_WITHOUT_OBJECT",
    "CREATED",
    "DELETED_FROM",
    "DELETED_KINDS",
    "DELETED_ON",
    "DELETED_WHY",
    "DOWNLOAD_SAID",
    "ENDS_ITS_THING",
    "FACES_CONFIRMED",
    "FACES_MATCHED",
    "FACES_WAITING",
    "FAILED_BECAUSE",
    "FEED",
    "FEED_MOST",
    "FIELD_WORDS",
    "FROM_ACT",
    "FROM_PASS",
    "FROM_PASS_MANY",
    "HERE",
    "KIND_BEFORE",
    "LINKED_KINDS",
    "MACHINE_ACTS",
    "MADE_READY",
    "MATCH_GRADES",
    "MEANS",
    "MERGE_NAMES_KEPT",
    "MOST_FIELDS",
    "MOST_ON",
    "PICTURE_ALONE",
    "PRESSED_ACTS",
    "RECORDED_NOTHING",
    "RENAMED_BECAUSE",
    "RENAMED_FOR_TOOL_ID",
    "SIFT",
    "SIFT_FROM",
    "SONG_FROM_ACOUSTID",
    "SONG_FROM_SAME_MUSIC",
    "SONG_FROM_SWAP",
    "STALE_FAILURES",
    "STALE_IN_A_TITLE",
    "SWAP",
    "SWAP_ENDED",
    "TASK_TAIL",
    "TASK_TAIL_MANY",
    "THE_TOP",
    "TOOK_BACK",
    "UNDONE",
    "VANTAGE_ENTITY",
    "VANTAGE_FILE",
    "VANTAGE_PERSON",
    "WHOSE",
    "YOU",
    "Act",
    "FilledField",
    "Group",
    "Line",
    "Part",
    "Piece",
    "Refusals",
    "Said",
    "_edited_line",
    "_filled_in",
    "_filled_words",
    "_grouped",
    "_song_line",
    "_template",
    "_took",
    "_value_said",
    "acoustid_answered",
    "added",
    "added_by",
    "agreed_to_be",
    "and_then",
    "as_then",
    "asked_and_found_nothing",
    "asked_and_waiting",
    "box_filled_named",
    "box_line",
    "boxes_recorded",
    "brought_named",
    "brought_over",
    "by_word",
    "capitalized",
    "carried_sentence",
    "copied_from",
    "copied_into",
    "copy_verb",
    "could_not",
    "counted_faces",
    "counted_line",
    "cover_changed",
    "deleted_here",
    "deleted_on",
    "deleted_where",
    "departures_kept",
    "details_read_again",
    "download_failed",
    "download_line",
    "download_row",
    "downloaded",
    "downloads_folded",
    "edited_fields",
    "edited_folded",
    "entity_added",
    "entity_created",
    "event_said",
    "faces",
    "faces_agreed",
    "faces_of_person",
    "faces_refused",
    "faces_set_aside",
    "faces_taken_off",
    "failed_because",
    "failure_today",
    "feed_folded",
    "feed_line",
    "fields_of",
    "filed_sentence",
    "filed_under",
    "files",
    "files_in_folder",
    "files_of_username",
    "filled_field",
    "filled_fields",
    "filled_folded",
    "filled_in_fold",
    "fingerprinted_by",
    "folder_named",
    "folder_of",
    "from_maker",
    "from_pass",
    "had_sift",
    "hidden_here",
    "how_sure",
    "kept_mine",
    "linked_before_recorded",
    "listed",
    "looked_for_faces",
    "machine_line",
    "made_ready",
    "many",
    "matched_sentence",
    "may_be_faces",
    "means",
    "members_added",
    "mention",
    "merged_line",
    "moved",
    "moved_into",
    "music_fingerprinted",
    "name_of",
    "named_on",
    "named_sentence",
    "nothing_to_fingerprint",
    "number_changed",
    "open_on",
    "passes_of",
    "payload_of",
    "people",
    "person_added",
    "person_refused",
    "plural",
    "pressed_act",
    "pressed_here",
    "processed",
    "processed_steps",
    "put_on",
    "read_its_meaning",
    "recognized",
    "recognized_face",
    "refused_as",
    "renamed",
    "ruled_out_of",
    "said",
    "setting_changed",
    "shared_with",
    "sift_from",
    "since_deleted",
    "since_removed",
    "song_named_here",
    "songs_moved",
    "subject_line_of",
    "swap_ended",
    "swap_started",
    "tagged_sentence",
    "tags",
    "taught_by",
    "text_of",
    "thing",
    "things_in",
    "times",
    "times_said",
    "today_words",
    "took_back_said",
    "undone",
    "username_opens",
    "usernames",
    "usernames_added",
    "watermark_found",
    "watermark_none",
    "watermark_refused",
]
