#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
"""The docs site's gates, run by the pre-commit hook, the closing chain and the docs workflow.

1. The generated pages match their declarations (`docs_generate.py --check`).
2. Vale, at the pinned version, over every page: a written page has no error; a generated page's
   errors (its words come from a registration) are a count per page that may only fall.
3. Every `Settings > ...` path is a plain deep link to the pane its first step names and a row that
   pane draws; the page opens with what it is and then a link to where it is; one task list; the
   Get started steps are numbered in the order they are read.
4. Every rail destination and every settings pane has a page, titled as the screen names it.
5. Every link inside the site reaches a page, and a link to another page names its heading.
6. Every menu, verb, Sort and Filter label is on its screen's page: a count that may only fall.

    python scripts/check_docs.py            every gate
    python scripts/check_docs.py --record   write a ratchet that fell
    python scripts/check_docs.py --write    write stale generated pages (the hook and the chain)
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import docs_client
import docs_menus
import docs_paths

ROOT = docs_client.ROOT
SITE = ROOT / "docs-site"
PAGES = SITE / "src" / "content" / "docs"
#: The settings pages' written openings: Vale reads them as written pages, because the page they
#: open is generated and carries the registry's copy, whose words are the screen's.
OPENINGS = SITE / "openings"
KEYS = SITE / "generated" / "keys.json"
RATCHETS = ROOT / "tests" / "gates" / "data" / "docs_ratchets.json"
VALE_VERSION = "3.24.0"
GENERATED = "<!-- GENERATED by scripts/docs_generate.py"
#: Pages that record what was true at each release: a path there names the screen as it was then.
HISTORY = {"whats-new"}

DISCORD = re.compile(r"https?://(?:www\.)?discord(?:\.gg|app\.com|\.com)/\S*", re.I)
#: The Discord invite, written once in astro.config.mjs; a page links to it by this placeholder.
DISCORD_LINK = "{{discord}}"
#: Get started, read in this order: each is "Step N: <title>", and any other page there is not.
STEPS = (
    "get-started/install-sift",
    "get-started/your-first-start",
    "get-started/add-your-folders",
    "get-started/your-first-download",
)
STEP = re.compile(r"^Step (\d+): (.+)$")
SIDEBAR_ORDER = re.compile(r"^\s+order:\s*(\d+)\s*$", re.M)
FENCE = re.compile(r"^```.*?^```", re.S | re.M)
FRONT_MATTER = re.compile(r"\A---\n(.*?)\n---\n", re.S)
NUMBERED = re.compile(r"^1\.\s", re.M)
LINK = re.compile(r"(?<!!)\[[^\]]*\]\(([^)\s]+)\)")
LINK_WORDS = re.compile(r"(?<!!)\[([^\]]*)\]\(([^)\s]+)\)")
SENTENCE_END = re.compile(r"(?<=[.?!])\s+(?=[A-Z\[`*])")
HEADING = re.compile(r"^#{2,6}\s+(.+?)\s*$", re.M)
EXPLICIT_ID = re.compile(r"""<a id="([^"]+)"></a>""")


def pages(root: Path = PAGES) -> dict[str, str]:
    """Every page by its address in the site (`settings/privacy`), as written."""
    found = {}
    for path in sorted(root.rglob("*.md")):
        rel = path.relative_to(root).with_suffix("").as_posix()
        found["" if rel == "index" else rel.removesuffix("/index")] = path.read_text(
            encoding="utf-8"
        )
    return found


def body(text: str) -> str:
    return FENCE.sub("", FRONT_MATTER.sub("", text))


def title(text: str) -> str:
    match = FRONT_MATTER.match(text)
    found = re.search(r"^title:\s*(.+)$", match.group(1), re.M) if match else None
    words = found.group(1).strip() if found else ""
    # A title holding ": " (Step 1: Install Sift) is quoted, as YAML needs; the title is inside.
    return words[1:-1] if len(words) > 1 and words[0] == words[-1] and words[0] in "'\"" else words


def check_paths(text: str, panes: dict[str, str], keys: dict[str, list[str]]) -> list[str]:
    found: list[str] = []
    linked = {m.start(1): (m.group(1), m.group(2)) for m in docs_paths.LINKED.finditer(text)}
    for match in docs_paths.START.finditer(text):
        if match.start() not in linked:
            plain = docs_paths.PLAIN.match(text, match.start())
            words = plain.group(0).strip() if plain else match.group(0)
            how = "is in code ticks" if text[match.start() - 1 : match.start()] == "`" else "is not"
            found.append(
                f"'{words}' {how} a plain deep link; write [{words}](/settings/<id>#<key>)"
            )
            continue
        path_text, address = linked[match.start()]
        steps = [step.strip() for step in path_text.split(">")][1:]
        deep = docs_paths.DEEP_LINK.match(address)
        if not deep:
            found.append(f"'{path_text}' links to {address}, which is not /settings/<id>#<key>")
            continue
        pane, key = deep.group(1), deep.group(2)
        if not steps or steps[0] not in panes:
            found.append(f"'{path_text}': no pane is labelled '{steps[0] if steps else ''}'")
        elif panes[steps[0]] != pane:
            found.append(
                f"'{path_text}' names {steps[0]} but links to '{pane}' ({steps[0]} is '{panes[steps[0]]}')"
            )
        if len(steps) > 1 and key is None:
            found.append(f"'{path_text}' names a row but its link has no #key")
        if key is not None and key not in keys.get(pane, []):
            found.append(f"'{path_text}': the pane '{pane}' draws no row '{key}'")
    return found


def check_shape(text: str) -> list[str]:
    found: list[str] = []
    if DISCORD.search(text):
        found.append(
            f"a Discord address; link to {DISCORD_LINK}, the invite astro.config.mjs names"
        )
    if len(NUMBERED.findall(text)) > 1:
        found.append("more than one numbered list; one task a page")
    paragraphs = [p.strip() for p in re.split(r"\n\s*\n", text) if p.strip()]
    first = next((p for p in paragraphs if not p.startswith(("#", "<", "|", "-", "1.", ">"))), "")
    sentences = [s for s in SENTENCE_END.split(first.replace("\n", " ")) if s]
    if len(sentences) < 2:
        found.append("the first paragraph needs two sentences: what it is, then how to open it")
    elif not any(LINK.search(s) for s in sentences[:2]):
        found.append("neither of the first two sentences links to where it is")
    return found


def slugger(text: str, seen: dict[str, int]) -> str:
    """A heading's id as the site writes it: lower case, punctuation out, spaces to hyphens."""
    plain = re.sub(r"\[([^\]]*)\]\([^)]*\)", r"\1", text)
    plain = re.sub(r"[`*_]", "", plain).lower()
    base = re.sub(r"[^\w\- ]", "", plain).replace(" ", "-")
    count = seen.get(base, 0)
    seen[base] = count + 1
    return base if count == 0 else f"{base}-{count}"


def anchors(text: str) -> set[str]:
    seen: dict[str, int] = {}
    return {
        "_top",
        *EXPLICIT_ID.findall(text),
        *(slugger(h, seen) for h in HEADING.findall(body(text))),
    }


def check_links(site: dict[str, str], routes: set[str]) -> list[str]:
    found: list[str] = []
    targets = {address: anchors(text) for address, text in site.items()}
    for address, text in site.items():
        for url in LINK.findall(body(text)):
            if (
                url.startswith(("http://", "https://", "mailto:", "/settings/"))
                or url == DISCORD_LINK
            ):
                continue
            if not url.startswith("/"):
                found.append(f"{address}: '{url}' is relative; link to /<page>/#<heading>")
                continue
            path, _, anchor = url.partition("#")
            page = path.strip("/")
            if page not in targets:
                if "/" + page.split("/")[0] not in routes:
                    found.append(f"{address}: '{url}' reaches no page")
            elif not anchor and page != address:
                found.append(
                    f"{address}: '{url}' names no heading; link to the page and its heading"
                )
            elif anchor and anchor not in targets[page]:
                found.append(f"{address}: '{url}' names a heading '{page}' does not have")
    return found


def check_coverage(site: dict[str, str]) -> list[str]:
    found: list[str] = []
    expected = {
        f"library/{docs_client.slug(item.label)}": item.label for item in docs_client.rail()
    }
    expected |= {f"settings/{pane.id}": pane.label for pane in docs_client.panes()}
    for address, label in expected.items():
        if address not in site:
            found.append(f"'{label}' has no page; write {address}.md")
        elif title(site[address]) != label:
            found.append(
                f"{address}.md is titled '{title(site[address])}'; the screen calls it '{label}'"
            )
    return found


def check_steps(site: dict[str, str]) -> list[str]:
    """Get started's steps are titled and ordered Step 1 to Step N, and a link names its step."""
    found: list[str] = []
    numbered: dict[str, tuple[str, str]] = {}
    for number, address in enumerate(STEPS, start=1):
        text = site.get(address, "")
        step = STEP.match(title(text))
        front = FRONT_MATTER.match(text)
        order = SIDEBAR_ORDER.search(front.group(1)) if front else None
        if not step or int(step.group(1)) != number:
            found.append(f"{address}.md is titled '{title(text)}'; write 'Step {number}: ...'")
        elif not order or int(order.group(1)) != number:
            found.append(f"{address}.md is Step {number} but its sidebar order is not {number}")
        else:
            numbered[address] = (title(text), step.group(2))
    for address, text in site.items():
        if address.startswith("get-started/") and address not in STEPS and STEP.match(title(text)):
            found.append(f"{address}.md is numbered, but Get started numbers {len(STEPS)} steps")
        for words, url in LINK_WORDS.findall(body(text)):
            page = url.partition("#")[0].strip("/")
            if page in numbered and words == numbered[page][1]:
                found.append(f"{address}: a link names '{words}'; name it '{numbered[page][0]}'")
    return found


def vale_binary() -> str | None:
    for candidate in (os.environ.get("DOCS_VALE"), shutil.which("vale")):
        if candidate and Path(candidate).is_file():
            return candidate
    return None


def vale_alerts() -> tuple[dict[str, list[str]], list[str]]:
    """Vale's errors by page, or why Vale could not answer: a missing or different Vale passes nothing."""
    binary = vale_binary()
    if binary is None:
        return {}, [f"Vale {VALE_VERSION} is not installed: put it on PATH or name it in DOCS_VALE"]
    version = subprocess.run(
        [binary, "--version"], capture_output=True, text=True, check=False
    ).stdout
    if VALE_VERSION not in version:
        return {}, [f"Vale is {version.strip()!r}; the docs are checked with {VALE_VERSION}"]
    command = [
        binary,
        "--config",
        ".vale.ini",
        "--output",
        "JSON",
        "--minAlertLevel",
        "error",
        "src/content/docs",
        OPENINGS.relative_to(SITE).as_posix(),
    ]
    run = subprocess.run(command, capture_output=True, text=True, cwd=SITE, check=False)
    try:
        alerts = json.loads(run.stdout or "{}")
    except json.JSONDecodeError:
        return {}, [f"Vale did not answer: {run.stderr.strip()[:300]}"]
    by_page: dict[str, list[str]] = {}
    for name, found in alerts.items():
        page = Path(name).as_posix().removeprefix("src/content/docs/").removesuffix(".md")
        by_page[page.removesuffix("/index")] = [
            f"{name}:{one['Line']}: {one['Check']}: {one['Message']}" for one in found
        ]
    return by_page, []


def ratchet(
    name: str, now: dict[str, int], kept: dict[str, dict[str, int]], record: bool
) -> list[str]:
    """A count per page that may only fall; a fall is written down with --record."""
    current = {page: n for page, n in sorted(now.items()) if n}
    if name not in kept:
        if record:
            kept[name] = current
            return []
        return [f"{name} has no record yet: python scripts/check_docs.py --record"]
    before: dict[str, int] = kept[name]
    rose = [
        f"{name}: {page} has {n}, the record says {before.get(page, 0)}"
        for page, n in current.items()
        if n > before.get(page, 0)
    ]
    if current != before and not rose:
        if record:
            kept[name] = current
        else:
            rose.append(f"{name} fell: record it with python scripts/check_docs.py --record")
    return rose


def page_findings(site: dict[str, str]) -> list[str]:
    panes = {pane.label: pane.id for pane in docs_client.panes()}
    keys = json.loads(KEYS.read_text(encoding="utf-8"))
    found = []
    for address, text in site.items():
        paths = [] if address in HISTORY else check_paths(body(text), panes, keys)
        found += [f"{address}: {one}" for one in paths + check_shape(body(text))]
    rail = {item.href for item in docs_client.rail()}
    return found + check_coverage(site) + check_steps(site) + check_links(site, rail)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--record", action="store_true")
    parser.add_argument(
        "--write", action="store_true", help="write stale generated pages, then refuse once"
    )
    args = parser.parse_args(argv)
    generator = [sys.executable, str(ROOT / "scripts" / "docs_generate.py")]
    stale = subprocess.run([*generator, "--check"], capture_output=True, text=True, check=False)
    # A generator that raised says so in its finding: an empty finding hides the cause.
    findings = (
        [(stale.stdout + stale.stderr).strip() or "the generator failed and said nothing"]
        if stale.returncode
        else []
    )
    if findings and args.write:
        subprocess.run(generator, check=True)
        findings = ["the generated pages above were written again: stage them"]
    site = pages()
    findings += page_findings(site)
    kept = json.loads(RATCHETS.read_text(encoding="utf-8")) if RATCHETS.is_file() else {}
    alerts, refused = vale_alerts()
    findings += refused
    made = {page for page, text in site.items() if GENERATED in text}
    findings += [line for page, lines in alerts.items() if page not in made for line in lines]
    counted = {page: len(lines) for page, lines in alerts.items() if page in made}
    findings += ratchet("vale_errors_on_generated_pages", counted, kept, args.record)
    missing = docs_menus.missing(site)
    findings += ratchet(
        "menu_labels_missing", {page: len(one) for page, one in missing.items()}, kept, args.record
    )
    if args.record:
        RATCHETS.write_text(
            json.dumps(kept, indent=2, sort_keys=True) + "\n", encoding="utf-8", newline="\n"
        )
    for line in findings:
        print(line)
    print(f"docs: {len(site)} pages, {len(findings)} findings")
    return 1 if findings else 0


if __name__ == "__main__":
    raise SystemExit(main())
