# SPDX-License-Identifier: AGPL-3.0-or-later
"""The Vale rules that hold Sift's own words, written from the vocabulary the copy gates read.

The screen's words live in one file, `tests/gates/data/vocabulary.json`, and the docs read the same
words through this module, so a word retired on the screen is retired in the docs in the same
commit. `docs_generate.py` writes ScreenWords.yml (matched ignoring case), ScreenWordsCase.yml
(matched as written) and Headings.yml (sentence case, Sift's names the exceptions).
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

HEADER = (
    "# GENERATED by scripts/docs_generate.py from tests/gates/data/vocabulary.json. Do not edit.\n"
)

#: The lists whose entries are a pattern, and the field each carries its replacement under.
PATTERN_LISTS = {
    "retired_words": "instead",
    "insider_phrases": "instead",
    "contractions": "instead",
    "paths": "instead",
    "phrasing": "instead",
    "spelling": "american",
    "typography": "instead",
    "lower_case_names": "instead",
}
#: The screen names the computer Sift runs on "this device"; the docs speak to the reader about it
#: (SecondPerson.yml), so a vocabulary entry that offers the screen's word offers the docs' instead.
DOCS_INSTEAD = {"this device": "your computer, or the computer Sift runs on"}
BRANDS = {"Settings", "Sift", "Windows", "macOS", "Linux", "Discord", "GitHub", "Docker", "API"}


def _yaml(text: str) -> str:
    return "'" + text.replace("'", "''") + "'"


def _compiles(pattern: str) -> bool:
    try:
        re.compile(pattern)
    except re.error:
        return False
    return True


def _docs(instead: str) -> str:
    """The word offered, as the docs say it; a screen label that holds it ("Benchmarking this
    device") is quoted, and stays."""
    for screen, docs in DOCS_INSTEAD.items():
        if instead.startswith(screen):
            return docs + instead[len(screen) :]
    return instead


def swaps(vocab: dict[str, Any]) -> tuple[dict[str, str], dict[str, str]]:
    """`(ignoring case, as written)`: every pattern a docs page must also obey."""
    loose: dict[str, str] = {}
    exact: dict[str, str] = {}
    # A word the vocabulary keeps for the sign-in screens (`sign_in`) is right on their pages too.
    kept = {word.strip() for word in vocab.get("sign_in", {}).get("words", [])}
    for entry in vocab["wrong_words"]:
        if entry["word"].strip() in kept:
            continue
        loose[r"\b" + re.escape(entry["word"].strip()) + r"\b"] = entry["instead"]
    for name, field in PATTERN_LISTS.items():
        for entry in vocab.get(name, []):
            if _compiles(entry["pattern"]):
                (exact if entry.get("case") else loose)[entry["pattern"]] = entry[field]
    for entry in vocab["banned_everywhere"]["entries"]:
        scope = entry.get("scope")
        if (scope is None or "docs/" in scope) and _compiles(entry["pattern"]):
            loose[entry["pattern"]] = entry["instead"]
    return {k: _docs(v) for k, v in loose.items()}, {k: _docs(v) for k, v in exact.items()}


def _substitution(table: dict[str, str], ignorecase: bool) -> str:
    lines = [
        HEADER,
        "extends: substitution\n",
        "message: \"Write %s, not '%s' (Sift's vocabulary).\"\n",
        "level: error\n",
        f"ignorecase: {'true' if ignorecase else 'false'}\n",
        "nonword: true\n",
        "swap:\n",
    ]
    lines += [
        f"  {_yaml(pattern)}: {_yaml(instead)}\n" for pattern, instead in sorted(table.items())
    ]
    return "".join(lines)


def _headings(vocab: dict[str, Any]) -> str:
    names = set(vocab["proper_names"]["words"]) | set(vocab["proper_names"]["phrases"]) | BRANDS
    names |= {noun["word"] for noun in vocab["nouns"] if noun["word"][:1].isupper()}
    lines = [
        HEADER,
        "extends: capitalization\n",
        "message: \"Write the heading '%s' in sentence case: a capital for the first word and for Sift's names only.\"\n",
        "level: error\n",
        "scope: heading\n",
        "match: $sentence\n",
        "indicators:\n  - ':'\n",
        "exceptions:\n",
    ]
    lines += [f"  - {_yaml(name)}\n" for name in sorted(names)]
    return "".join(lines)


def files(vocabulary: Path, styles: Path) -> dict[Path, str]:
    vocab = json.loads(vocabulary.read_text(encoding="utf-8"))
    loose, exact = swaps(vocab)
    return {
        styles / "ScreenWords.yml": _substitution(loose, True),
        styles / "ScreenWordsCase.yml": _substitution(exact, False),
        styles / "Headings.yml": _headings(vocab),
    }
