# SPDX-License-Identifier: AGPL-3.0-or-later
"""Write the docs site's generated pages from the declarations they describe.

The Settings reference (one page per pane, every registered setting on the pane that draws it),
the Tasks reference (on the Tasks and Activity page), What's new (from CHANGELOG.md), the API
reference (from frontend/openapi.json), the Vale rules for Sift's words (from the vocabulary) and
`keys.json`, the map of pane to row ids the path gate reads. A fix to a sentence is a fix to its
declaration; these files are never edited by hand.

    python scripts/docs_generate.py           write every generated file
    python scripts/docs_generate.py --check   exit 1 naming each file that is out of date
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent))

import docs_api
import docs_client
import docs_paths
import docs_vale_rules

ROOT = docs_client.ROOT
SITE = ROOT / "docs-site"
PAGES = SITE / "src" / "content" / "docs"
KEYS = SITE / "generated" / "keys.json"
SIDEBAR = SITE / "generated" / "sidebar.json"
SEARCH_MODULES = ROOT / "frontend" / "src" / "lib" / "settings-ui"
#: Each Settings page's written opening, `<pane id>.md`: what the pane is for, the task somebody
#: opens it for, and what it draws that is not a registered setting. Read here so the page stays
#: one generated file while the words a person must write live in a file a person edits.
OPENINGS = SITE / "openings" / "settings"
HEADER = "<!-- GENERATED by scripts/docs_generate.py from {source}. Edit the source, never this page. -->"
WHO = {"app": "an admin, for everyone on this Sift", "user": "each User, for themselves"}
_ENTRY = re.compile(r"\{[^{}]*\}")
_FIELD = re.compile(r"\b(key|section):\s*'([^']+)'")


def _loaded() -> tuple[dict[str, Any], dict[str, Any], dict[str, str]]:
    sys.path.insert(0, str(ROOT))
    from tests.gates.test_every_setting_reaches_a_screen import DRAWN_NOWHERE_ON_PURPOSE

    import sift.main  # noqa: F401  (registers every setting and task)
    from sift.kernel.jobs.schedules import registered_schedules
    from sift.kernel.settings_registry import registered_settings

    return registered_settings(), registered_schedules(), DRAWN_NOWHERE_ON_PURPOSE


_ASCII = {
    " \u2014 ": ": ",
    "\u2014": ": ",
    "\u2013": " to ",
    "\u2018": "'",
    "\u2019": "'",
    "\u201c": '"',
    "\u201d": '"',
    "\u2026": "...",
}


def _ascii(text: str) -> str:
    """The tree is ASCII: the screen's dashes and curly quotes, as the docs write them."""
    for one, instead in _ASCII.items():
        text = text.replace(one, instead)
    return text


def _text(words: str) -> str:
    """Prose for a Markdown page: an angle bracket outside code ticks is a character, never a tag."""
    parts = words.split("`")
    return "`".join(part if at % 2 else part.replace("<", "&lt;") for at, part in enumerate(parts))


def _value(setting: Any, value: Any) -> str:
    if setting.choices is not None and value in setting.choices:
        return str(setting.choice_labels[setting.choices.index(value)])
    if isinstance(value, bool):
        return "On" if value else "Off"
    if value in (0, None) and setting.automatic_label:
        return str(setting.automatic_label)
    if value in ("", None, []):
        return "empty"
    return f"{value} {setting.unit}" if setting.unit else str(value)


def _range(setting: Any) -> str | None:
    if setting.minimum is None and setting.maximum is None:
        return None
    unit = f" {setting.unit}" if setting.unit else ""
    low = (
        setting.automatic_label
        if setting.minimum == 0 and setting.automatic_label
        else setting.minimum
    )
    if setting.maximum is None:
        return f"{low}{unit} or more"
    return (
        f"{low} to {setting.maximum}{unit}"
        if setting.minimum is not None
        else f"up to {setting.maximum}{unit}"
    )


class Index:
    """Every row each pane draws, so a path written in help copy is linked to its row."""

    def __init__(self, settings: dict[str, Any], excused: dict[str, str]) -> None:
        self.panes = docs_client.panes()
        self.by_label = {pane.label: pane for pane in self.panes}
        self.rows: dict[str, list[tuple[str, Any]]] = {pane.id: [] for pane in self.panes}
        for key, setting in settings.items():
            if key in excused:
                continue
            at = docs_client.drawn_at(setting.section, key)
            self.rows.setdefault(at.pane, []).append((at.key or key, setting))
        self.hand = self._hand_rows()

    @staticmethod
    def _hand_rows() -> dict[str, set[str]]:
        found: dict[str, set[str]] = {}
        for module in sorted(SEARCH_MODULES.glob("*.search.ts")):
            text = module.read_text(encoding="utf-8")
            for entry in _ENTRY.findall(text[text.find("SEARCHABLE") :]):
                fields = dict(_FIELD.findall(entry))
                if "key" in fields and "section" in fields:
                    at = docs_client.resolve(
                        fields["section"], fields["key"], *docs_client.resolver()
                    )
                    found.setdefault(at.pane, set()).add(at.key or fields["key"])
        return found

    def keys(self, tasks: dict[str, Any]) -> dict[str, list[str]]:
        every = {pane: {key for key, _ in rows} for pane, rows in self.rows.items()}
        every["tasks"].update(task.when_key for task in tasks.values() if task.shown)
        for pane, keys in self.hand.items():
            every.setdefault(pane, set()).update(keys)
        return {pane: sorted(keys) for pane, keys in sorted(every.items())}

    def link(self, path_text: str) -> str:
        """A path as a link to its pane and row; one naming no pane stays words, and the gate says so."""
        crumbs = [step.strip() for step in path_text.split(">")][1:]
        pane = self.by_label.get(crumbs[0]) if crumbs else None
        if pane is None:
            return path_text
        named = {setting.label: key for key, setting in self.rows.get(pane.id, [])}
        key = next((named[crumb] for crumb in reversed(crumbs[1:]) if crumb in named), None)
        return docs_paths.link(path_text, f"/settings/{pane.id}{'#' + key if key else ''}")

    def _plain(self, match: re.Match[str]) -> str:
        """A plain path linked, the space after it kept outside the link."""
        path = match.group(0).rstrip()
        return self.link(path) + match.group(0)[len(path) :]

    def _paths(self, words: str, plain: bool) -> str:
        """Each ticked path out of its ticks and linked, and with `plain` each plain one too."""
        out = []
        for at, part in enumerate(_text(words).split("`")):
            if at % 2 == 0:
                out.append(docs_paths.PLAIN.sub(self._plain, part) if plain else part)
            elif docs_paths.START.match(part):
                out.append(self.link(part))
            else:
                out.append(f"`{part}`")
        return "".join(out)

    def linked(self, words: str) -> str:
        """The changelog: its paths are in ticks, as the tree's documents write them."""
        return self._paths(words, plain=False)

    def copy(self, words: str) -> str:
        """A registration's help or disclosure: the screen draws its paths as plain text."""
        return self._paths(words, plain=True)


def _row(index: Index, pane: Any, key: str, setting: Any) -> list[str]:
    lines = [f'<a id="{key}"></a>', "", f"### {setting.label}", "", index.copy(setting.help), ""]
    if setting.disclosure:
        lines += [index.copy(setting.disclosure), ""]
    path = docs_paths.link(
        f"Settings > {pane.label} > {setting.label}", f"/settings/{pane.id}#{key}"
    )
    lines.append(f"- **Path**: {path}")
    lines.append(f"- **Default**: {_value(setting, setting.default)}")
    if setting.choices is not None:
        lines.append(f"- **Choices**: {', '.join(setting.choice_labels)}")
    elif (span := _range(setting)) is not None:
        lines.append(f"- **Range**: {span}")
    lines += [f"- **Who sets it**: {WHO[str(setting.scope)]}", ""]
    return lines


def _task(index: Index, pane: Any, task: Any, settings: dict[str, Any]) -> list[str]:
    when = settings.get(task.when_key)
    lines = [f'<a id="{task.when_key}"></a>', "", f"### {task.title}", "", _text(task.explain), ""]
    path = docs_paths.link(
        f"Settings > {pane.label} > {task.title}", f"/settings/{pane.id}#{task.when_key}"
    )
    lines.append(f"- **Path**: {path}")
    if when is not None:
        lines.append(f"- **When it runs**: {_value(when, when.default)}")
        lines.append(f"- **Choices**: {', '.join(task.when_labels().values())}")
    beside = [settings[key] for key in task.setting_keys if key in settings]
    if beside:
        lines.append(f"- **Its settings**: {', '.join(one.label for one in beside)}")
    if task.set_in:
        owner = next((one for one in index.panes if one.id == task.set_in), None)
        if owner is not None:
            more = docs_paths.link(f"Settings > {owner.label}", f"/settings/{owner.id}")
            lines.append(f"- **More in**: {more}")
    return [*lines, "- **Who sets it**: an admin, for everyone on this Sift", ""]


def opening(pane: Any) -> list[str]:
    """The pane's written opening, or the one sentence every pane can say without a person."""
    written = OPENINGS / f"{pane.id}.md"
    if written.is_file():
        return [written.read_text(encoding="utf-8").strip("\n"), ""]
    return [
        "This page lists every setting on the pane, in the order Sift declares them. "
        f"To open the pane, go to {docs_paths.link(f'Settings > {pane.label}', f'/settings/{pane.id}')}.",
        "",
    ]


def settings_page(index: Index, pane: Any, settings: dict[str, Any], tasks: dict[str, Any]) -> str:
    when_keys = {task.when_key for task in tasks.values()}
    lines = [
        "---",
        f"title: {pane.label}",
        f"description: What each setting in {pane.label} does.",
        "---",
        "",
        HEADER.format(source="the settings registry and the client's sections.ts"),
        "",
        *opening(pane),
    ]
    shown = [task for task in tasks.values() if task.shown] if pane.id == "tasks" else []
    if shown:
        lines += ["## Tasks", ""]
        for task in shown:
            lines += _task(index, pane, task, settings)
    rows = [
        (key, one) for key, one in index.rows.get(pane.id, []) if not (shown and key in when_keys)
    ]
    if rows:
        lines += ["## Settings" if shown else "## Every setting", ""]
        for key, setting in rows:
            lines += _row(index, pane, key, setting)
    if not shown and not rows:
        lines += [
            "Nothing on this pane is a stored setting.",
            "",
        ]
    return "\n".join(lines).rstrip("\n") + "\n"


def whats_new(index: Index) -> str:
    """CHANGELOG.md as a page: its title and opening paragraph give way to the page's own."""
    text = (ROOT / "CHANGELOG.md").read_text(encoding="utf-8")
    body = text[text.index("\n## ") + 1 :] if "\n## " in text else ""
    head = [
        "---",
        "title: What's new",
        "description: What each release of Sift changes, newest first.",
        "---",
        "",
        HEADER.format(source="CHANGELOG.md"),
        "",
        "What's new lists what each release of Sift changes for you, newest first. "
        "To see the version you run, open "
        f"{docs_paths.link('Settings > Updates and Info', '/settings/updates')}.",
        "",
    ]
    return "\n".join(head) + index.linked(body).rstrip("\n") + "\n"


def sidebar(index: Index) -> dict[str, Any]:
    """The site's menu in the screen's order, and where each rail address is described."""
    rail = docs_client.rail()
    groups: dict[str, list[str]] = {}
    for pane in index.panes:
        groups.setdefault(pane.group, []).append(f"settings/{pane.id}")
    return {
        "library": [f"library/{docs_client.slug(item.label)}" for item in rail],
        "settings": [{"label": name, "items": items} for name, items in groups.items()],
        "routes": {item.href: f"/library/{docs_client.slug(item.label)}/" for item in rail},
    }


def generated() -> dict[Path, str]:
    """Every generated file and what it should hold."""
    settings, tasks, excused = _loaded()
    index = Index(settings, excused)
    files = {
        PAGES / "settings" / f"{pane.id}.md": settings_page(index, pane, settings, tasks)
        for pane in index.panes
    }
    files[PAGES / "whats-new.md"] = whats_new(index)
    files[PAGES / "developers" / "api.md"] = docs_api.page(
        ROOT / "frontend" / "openapi.json", HEADER
    )
    files[KEYS] = json.dumps(index.keys(tasks), indent=2, sort_keys=True) + "\n"
    files[SIDEBAR] = json.dumps(sidebar(index), indent=2) + "\n"
    files.update(
        docs_vale_rules.files(
            ROOT / "tests" / "gates" / "data" / "vocabulary.json", SITE / "styles" / "Sift"
        )
    )
    return files


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    stale = []
    for path, text in generated().items():
        text = _ascii(text)
        if path.is_file() and path.read_text(encoding="utf-8") == text:
            continue
        stale.append(path.relative_to(ROOT).as_posix())
        if not args.check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8", newline="\n")
    verb = "out of date" if args.check else "written"
    for one in stale:
        print(f"{verb}: {one}")
    if args.check and stale:
        print("run: python scripts/docs_generate.py")
    return 1 if args.check and stale else 0


if __name__ == "__main__":
    raise SystemExit(main())
