# SPDX-License-Identifier: AGPL-3.0-or-later
"""The durable queue: enqueue, claim, and every state change a job can undergo.

The whole design rests on one statement. A worker takes a job with a single
`UPDATE ... RETURNING` that both selects the row and marks it taken, so two workers racing for
the same job cannot both win: one of them updates it, the other's subquery no longer matches
and it comes back empty-handed. Nothing is held in memory between the two halves, because there
is no gap between them to hold anything in.

That is also what makes a crash safe, and it is worth being precise about why. If the process
dies mid-job the row is simply still `running` with nobody running it, and boot recovery puts it
back. If it dies mid-*claim*, SQLite rolls the transaction back and the row was never claimed at
all. Neither case needs bookkeeping, a lease table, or a reconciliation pass. Do not add one.

The other half of the design is the fence. A claim stamps `claimed_by`, and every subsequent
write about that job carries it: `WHERE id = ? AND state = 'running' AND claimed_by = ?`. So a
worker that hung, had its job requeued by the watchdog, and then woke up cannot report `done` on
work another worker has since redone. It finds its update matched nothing, which is how it learns
it lost the job.
"""

from __future__ import annotations

from sift.kernel.jobs.queue_claim import (
    _CLAIM,
    _CLAIM_EXCLUDING,
    _CLAIM_ONLY,
    _EXCLUSIVE_HELD,
    _PAUSE_CLAIMABLE,
    _RUNNING_BY_TYPE,
    _SOMEBODY_WAITING,
    Claiming,
    _capped,
    _claimed,
)
from sift.kernel.jobs.queue_controls import (
    _CALL_OFF_THE_HEAD,
    _CALL_OFF_THE_HEADS,
    _CANCEL_EVERYTHING,
    _CANCEL_TREE,
    _CLEAR_ALL_CANCELED,
    _CLEAR_ALL_FAILED,
    _HEADS_PER_ASK,
    _MOST_CLEAR_PASSES,
    _PRUNE_SETTLED,
    _RETRY,
    _RETRY_ALL_CANCELED,
    _RETRY_ALL_FAILED,
    _ROLL_UP_CANCELED,
    Controls,
)
from sift.kernel.jobs.queue_core import (
    _ROLL_UP,
    SUMMARY_FRESH_FOR_SECONDS,
)
from sift.kernel.jobs.queue_enqueue import (
    _INSERT,
    _NAME_REQUESTER,
    _PENDING_LIKE,
    _PUT_OFF,
    _RAISE_PRIORITY,
    _RETIME_WAITING,
    _RUN_NOW,
    _WITHDRAW_WAITING,
    Enqueuing,
)
from sift.kernel.jobs.queue_handoffs import (
    _USER_STILL_THERE,
)
from sift.kernel.jobs.queue_pages import (
    _AND,
    _COUNT_HEAD,
    _FAMILY_FILE,
    _FAMILY_TALLY_HEAD,
    _FAMILY_TALLY_TAIL,
    _FILTERS,
    _LIST_HEAD,
    _LIST_ORDER,
    _PAGE,
    _PAGE_FILTERS,
    _POSITIONS,
    _QUIET_BY_STATE,
    _QUIET_COUNT_HEAD,
    _STEP_COUNTS,
    _STEPS_PAGE,
    _STEPS_TOTAL,
    _TOP_OF,
    _UPKEEP_COUNT_HEAD,
    _WHERE,
    STEP_COUNT_CAP,
    Pages,
    _family_tally,
    _list_page,
    _list_total,
    _quiet_total,
    _upkeep_total,
    _where,
)
from sift.kernel.jobs.queue_reads import (
    _ASKED_ABOUT_PER_READ,
    _BURST_START,
    _DONE_LATELY,
    _DUE_BY_TYPE,
    _LIVE_ASSET_IDS,
    _LIVE_BY_PRESS,
    _LIVE_BY_TYPE,
    _LIVE_FILES,
    _LIVE_LIKE,
    _LIVE_PAYLOADS,
    _LIVE_PRODUCTS,
    _LIVE_SUMMARY,
    _LIVE_TOPS,
    _NEWEST_OF_TYPE,
    _NEXT_SCHEDULED,
    _NEXT_SCHEDULED_OF,
    _OUTSTANDING,
    _PARKED_UNTIL_UNLOCKED,
    _PRESSED_SINCE,
    _QUEUED_PAYLOADS,
    _SETTLED_IN_RUN,
    _TALLIES,
    _UNFINISHED_AMONG,
    _UNFINISHED_BY_TYPE,
    RECENT_WORK_SECONDS,
    Reads,
)
from sift.kernel.jobs.queue_rows import (
    _ABSOLUTE_PATH,
    _FOLDED,
    _FOLDED_STRONGEST_FIRST,
    _PATH_SEPARATORS,
    _UNFINISHED,
    CANCELABLE_STATES,
    DEFAULT_PAGE_SIZE,
    MAX_PAGE_SIZE,
    PAUSE_WITHDRAWN,
    STOP_TO_CANCEL,
    STOP_TO_PAUSE,
    TERMINAL_STATES,
    UNLOCK_WAIT,
    Beat,
    FamilyFailure,
    Job,
    JobBlocked,
    JobCanceled,
    JobFailedPermanently,
    JobHeld,
    JobPage,
    JobPaused,
    JobState,
    LiveProducts,
    LiveWork,
    PressedWork,
    StepCounts,
    StepsPage,
    TaskRun,
    UnknownJobType,
    WaitingForPassword,
    WorkKind,
    WorkSummary,
    _check_payload,
    _fetch,
    _for_the_record,
    _looks_like_a_path,
    _products_named,
    _to_job,
    folded_state,
    waits_for_password,
)
from sift.kernel.jobs.queue_runs import (
    _A_RUN_ENDED,
    _A_RUN_IS,
    _STARTED_BY,
    _TASK_RUNS,
    ANYONE,
    STARTED_BY_PRESS,
    STARTED_BY_SCHEDULE,
    TaskRuns,
    _task_runs,
    _task_runs_from,
)
from sift.kernel.jobs.queue_settle import (
    _ASK_TO_PAUSE,
    _BLOCK,
    _COMPLETE,
    _FAIL,
    _FAIL_PERMANENTLY,
    _HANDED_BACK,
    _HEARTBEAT,
    _HOLD,
    _PAUSE_QUEUED,
    _PAUSE_RUNNING,
    _RECLAIM_EXHAUSTED,
    _RECLAIM_REQUEUE,
    _RELEASE_RUNNING,
    _RESUME,
    _SET_NOTE,
    _SET_PROGRESS,
    _SET_UNITS,
    _UNASK_PAUSE,
    _UNBLOCK,
    Settling,
)
from sift.kernel.jobs.queue_switchboard import (
    _DEMAND_BY_TYPE,
    _HELD_BY_TYPE,
    READINESS_FRESH_FOR_SECONDS,
)

#: Every name the queue's modules define, so callers and the statement gates read one door.
__all__ = [
    "ANYONE",
    "CANCELABLE_STATES",
    "DEFAULT_PAGE_SIZE",
    "MAX_PAGE_SIZE",
    "PAUSE_WITHDRAWN",
    "READINESS_FRESH_FOR_SECONDS",
    "RECENT_WORK_SECONDS",
    "STARTED_BY_PRESS",
    "STARTED_BY_SCHEDULE",
    "STEP_COUNT_CAP",
    "STOP_TO_CANCEL",
    "STOP_TO_PAUSE",
    "SUMMARY_FRESH_FOR_SECONDS",
    "TERMINAL_STATES",
    "UNLOCK_WAIT",
    "_ABSOLUTE_PATH",
    "_AND",
    "_ASKED_ABOUT_PER_READ",
    "_ASK_TO_PAUSE",
    "_A_RUN_ENDED",
    "_A_RUN_IS",
    "_BLOCK",
    "_BURST_START",
    "_CALL_OFF_THE_HEAD",
    "_CALL_OFF_THE_HEADS",
    "_CANCEL_EVERYTHING",
    "_CANCEL_TREE",
    "_CLAIM",
    "_CLAIM_EXCLUDING",
    "_CLAIM_ONLY",
    "_CLEAR_ALL_CANCELED",
    "_CLEAR_ALL_FAILED",
    "_COMPLETE",
    "_COUNT_HEAD",
    "_DEMAND_BY_TYPE",
    "_DONE_LATELY",
    "_DUE_BY_TYPE",
    "_EXCLUSIVE_HELD",
    "_FAIL",
    "_FAIL_PERMANENTLY",
    "_FAMILY_FILE",
    "_FAMILY_TALLY_HEAD",
    "_FAMILY_TALLY_TAIL",
    "_FILTERS",
    "_FOLDED",
    "_FOLDED_STRONGEST_FIRST",
    "_HANDED_BACK",
    "_HEADS_PER_ASK",
    "_HEARTBEAT",
    "_HELD_BY_TYPE",
    "_HOLD",
    "_INSERT",
    "_LIST_HEAD",
    "_LIST_ORDER",
    "_LIVE_ASSET_IDS",
    "_LIVE_BY_PRESS",
    "_LIVE_BY_TYPE",
    "_LIVE_FILES",
    "_LIVE_LIKE",
    "_LIVE_PAYLOADS",
    "_LIVE_PRODUCTS",
    "_LIVE_SUMMARY",
    "_LIVE_TOPS",
    "_MOST_CLEAR_PASSES",
    "_NAME_REQUESTER",
    "_NEWEST_OF_TYPE",
    "_NEXT_SCHEDULED",
    "_NEXT_SCHEDULED_OF",
    "_OUTSTANDING",
    "_PAGE",
    "_PAGE_FILTERS",
    "_PARKED_UNTIL_UNLOCKED",
    "_PATH_SEPARATORS",
    "_PAUSE_CLAIMABLE",
    "_PAUSE_QUEUED",
    "_PAUSE_RUNNING",
    "_PENDING_LIKE",
    "_POSITIONS",
    "_PRESSED_SINCE",
    "_PRUNE_SETTLED",
    "_PUT_OFF",
    "_QUEUED_PAYLOADS",
    "_QUIET_BY_STATE",
    "_QUIET_COUNT_HEAD",
    "_RAISE_PRIORITY",
    "_RECLAIM_EXHAUSTED",
    "_RECLAIM_REQUEUE",
    "_RELEASE_RUNNING",
    "_RESUME",
    "_RETIME_WAITING",
    "_RETRY",
    "_RETRY_ALL_CANCELED",
    "_RETRY_ALL_FAILED",
    "_ROLL_UP",
    "_ROLL_UP_CANCELED",
    "_RUNNING_BY_TYPE",
    "_RUN_NOW",
    "_SETTLED_IN_RUN",
    "_SET_NOTE",
    "_SET_PROGRESS",
    "_SET_UNITS",
    "_SOMEBODY_WAITING",
    "_STARTED_BY",
    "_STEPS_PAGE",
    "_STEPS_TOTAL",
    "_STEP_COUNTS",
    "_TALLIES",
    "_TASK_RUNS",
    "_TOP_OF",
    "_UNASK_PAUSE",
    "_UNBLOCK",
    "_UNFINISHED",
    "_UNFINISHED_AMONG",
    "_UNFINISHED_BY_TYPE",
    "_UPKEEP_COUNT_HEAD",
    "_USER_STILL_THERE",
    "_WHERE",
    "_WITHDRAW_WAITING",
    "Beat",
    "FamilyFailure",
    "Job",
    "JobBlocked",
    "JobCanceled",
    "JobFailedPermanently",
    "JobHeld",
    "JobPage",
    "JobPaused",
    "JobQueue",
    "JobState",
    "LiveProducts",
    "LiveWork",
    "PressedWork",
    "StepCounts",
    "StepsPage",
    "TaskRun",
    "UnknownJobType",
    "WaitingForPassword",
    "WorkKind",
    "WorkSummary",
    "_capped",
    "_check_payload",
    "_claimed",
    "_family_tally",
    "_fetch",
    "_for_the_record",
    "_list_page",
    "_list_total",
    "_looks_like_a_path",
    "_products_named",
    "_quiet_total",
    "_task_runs",
    "_task_runs_from",
    "_to_job",
    "_upkeep_total",
    "_where",
    "folded_state",
    "waits_for_password",
]


class JobQueue(Enqueuing, Claiming, Settling, Controls, Reads, Pages, TaskRuns):
    """The queue. One per database, held on the application rather than in a module global.

    Each concern is a part of its own module, and this class is all of them together: putting
    work in, taking it out, finishing it, the operator's controls, the reads, the pages and the
    task runs, over one database, one clock and one door for writes (`QueueCore`).
    """
