# SPDX-License-Identifier: AGPL-3.0-or-later
"""The switches for the stash-boxes, and one rule per field they can fill in.

Two kinds of setting here and they are different in shape, which is why they are declared in two
loops rather than one list.

**The switches** are what the feature does at all: whether files are matched against the stash-boxes,
whether a certain match may apply itself, and whether a bulk run may invent rows. Each is written
out, because each says something particular.

**The rules** are one per field, and they are GENERATED from the record registry. Between them a
person, a site, a tag and a file have dozens of fields a stash-box can fill in, and writing that
many declarations by hand is that many chances for the label on the settings screen to disagree
with the label on the record. So the label comes from the registry, and a field added next year
arrives with a rule and a control and nobody has to remember either.

That is the same reasoning the record screens are generated by, and it has the same consequence: the
settings screen has no list of enrichment fields anywhere in it.
"""

from __future__ import annotations

from sift.kernel.enrichment import DEFAULT_STRATEGY, Strategy, strategy_key
from sift.kernel.records import Subject, fields_of
from sift.kernel.seams import SettingsSeam
from sift.kernel.settings_registry import ReadBy, register_setting
from sift.slices.stash_boxes.known_boxes import KNOWN_BOXES

# Its own section: these forty-odd field rules are one question, and a section should answer one.
SECTION = "Stash-boxes"

#: Whether files are matched against the stash-boxes at all.
#:
#: Off by default, and it is a consent gate rather than a default that happens to start off: what it
#: turns on is a fingerprint of every file in the library being sent to three public services.
SCAN_KEY = "stash_boxes.scan"
#: Whether a batch of NEW files is asked about on its own, once their fingerprints are ready.
#:
#: Under `SCAN_KEY` and never instead of it: off, the stash-boxes are asked only when somebody
#: presses Enrich library. On by default because it is the point of switching enriching on at all,
#: and the consent gate is the switch above it: this one decides when, not whether. The run it
#: allows is Sift's own act and is written down as such.
ASK_NEW_FILES_KEY = "stash_boxes.ask_new_files"

#: Whether a match on an exact-file hash may write without being asked, ON A RUN NOBODY PRESSED.
#:
#: Only an exact hash the scene itself carries (`service.grade_of`). A perceptual match is fuzzy and
#: capped by nature (see the adapter), so it is a suggestion for somebody to agree with and never a
#: decision. Off by default even so.
#:
#: It governs only the runs nobody pressed. A press is its own consent: a pressed Auto-enrich
#: accepts what is certain (`jobs.scan` reads the press's own `apply`), as Auto-enrich on a person
#: applies its one sure match; a pressed Enrich (the chooser) leaves everything waiting. This switch
#: decides only for the pass that asks about new files on its own. See `apply_for`.
AUTO_APPLY_KEY = "stash_boxes.apply_certain"

#: Whether a record shows everything a stash-box can fill in, or only what somebody reads at a
#: glance.
#:
#: Off by default and display-only: it changes what is DRAWN and never what is stored, so turning
#: it on and off again leaves the library exactly as it was. It exists because a person's record
#: carries eleven fields that only a stash-box ever fills in (gender, ethnicity, eye colour,
#: height, breast type, two career years, tattoos, piercings, a disambiguation and an age), and on
#: a library where nothing has been looked up they are eleven dashes in a row. A record has to be
#: readable before anybody has connected anything.
SHOW_EVERY_FIELD_KEY = "records.show_every_field"

#: Whether a run nobody is watching may INVENT a person, a site or a tag it has never heard of.
#:
#: Per kind, and on for each. Two things run without somebody in front of them (a certain match
#: applying itself, and Auto-enrich), and without this a page of matches whose people are all new
#: would file nothing at all. What a stash-box creates says so on its row, so it can be filtered
#: by and removed in one pass if it is not wanted.
#:
#: Per kind because the three are different decisions: a stash-box's tag vocabulary is somebody
#: else's filing system and can crowd a tag list, while the people on a file are usually wanted.
#:
#: These are the only kinds that can be created (`may_create` is asked for a person, a site and a
#: tag and nothing else), so the loop below is over the kinds themselves.
INVENTABLE: tuple[Subject, ...] = (Subject.PERSON, Subject.SITE, Subject.TAG)


def invent_key(subject: Subject) -> str:
    """The switch for one kind. Built rather than written out, for the reason the field rules are:
    a key spelled in two places is a key that can come to be spelled two ways."""
    return f"stash_boxes.invent.{subject.value}"


#: What each kind is called on its own switch, in the plural, because the switch is about many.
_INVENT_LABEL = {
    Subject.PERSON: "people",
    Subject.SITE: "Sites",
    Subject.TAG: "tags",
}


async def may_invent(settings: SettingsSeam) -> frozenset[str]:
    """Which kinds a run nobody is watching may create, as the kind values `may_create` reads.

    The one place the three switches are turned into an answer. Both callers (the certain match
    and Auto-enrich) ask this rather than reading the keys themselves, because a second reader
    would be a second place for a switch somebody turned off to be read wrongly, and reading it
    wrongly here means inventing rows in somebody's library after they said no.
    """
    allowed: set[str] = set()
    for subject in INVENTABLE:
        if bool(await settings.get_app(invent_key(subject))):
            allowed.add(subject.value)
    return frozenset(allowed)


def _invent_switches() -> None:
    """One switch per kind that can be invented. See `INVENTABLE`."""
    for subject in INVENTABLE:
        register_setting(
            key=invent_key(subject),
            scope="app",
            default=True,
            section=SECTION,
            # Six words at most, which is what a settings label gets: a label needing more is
            # answering the question its help is for. "New" carries "not heard of" in one word.
            label=f"Create new {_INVENT_LABEL[subject]}",
            disclosure=(
                "Applies only to automatic lookups and to Auto-enrich. What you confirm yourself "
                "always creates what you select."
            ),
            help=(
                f"When off, {_INVENT_LABEL[subject]} a stash-box names that your library doesn't "
                "have are skipped."
            ),
        )


#: WHICH stash-box the unattended passes ask, or every switched-on one.
#:
#: Empty is all of them and is the default: a sweep asks every box that is switched on, and three
#: boxes that disagree about a scene are three answers somebody can compare. What this adds is the
#: other way of working (one library, one source of truth), without switching two boxes off and
#: remembering to switch them back.
#:
#: The box's own WORD, never its id and never its name. An id moves the moment somebody removes and
#: re-adds a box, and a name is whatever they typed into the field. See `known_boxes`, which is
#: also where the honest limit is written down: a box Sift has no word for cannot be singled out.
#:
#: It narrows the UNATTENDED passes and the press that hands one over, not the box list, and not a
#: chooser somebody has open. A box left out here is still switched on, still answers a search, and
#: still draws its marks; what it stops doing is being asked by a run nobody is watching.
#:
#: Sift's OWN passes are untouched by it, deliberately. Faces, filenames, watermarks and the
#: semantic index each have their own switch in their own section, and a second control for one
#: switch is two places for one truth to be read from. See the help.
AUTO_BOX_KEY = "stash_boxes.auto_box"

#: Every box the choice offers, and every word beside it, from the one file that knows them.
_AUTO_BOX_WORDS = ("", *(word for word, _spelling in KNOWN_BOXES))
_AUTO_BOX_LABELS = ("All stash-boxes", *(spelling for _word, spelling in KNOWN_BOXES))


async def auto_box(settings: SettingsSeam) -> str | None:
    """Which box the unattended passes may ask, or None for every switched-on one.

    The one place the setting is turned into an answer, for the reason `may_invent` is one place:
    a second reader would be a second chance to read an empty value as a box called "" and ask
    nobody at all.
    """
    held = str(await settings.get_app(AUTO_BOX_KEY) or "").strip().lower()
    return held or None


#: The word a PRESS sends for "every switched-on box", which is not the same answer as no word.
#:
#: Two answers need two spellings. If the flyout's "All stash-boxes" row sent nothing, as a press
#: that names no box does, the route could not tell "ask them all" from "ask whatever is set up",
#: against the model's own sentence that absent means whatever is set up. Nothing is the SETTING
#: (see `box_for`) and this is every box.
#:
#: Not a box's word and never can be: a box's word comes from `known_boxes`, and "all" is not one.
EVERY_BOX = "all"


#: What a press says when every stash-box is turned off, and when the one it would ask is.
#:
#: A press that queues work which then asks nobody reads as a broken button: the start route
#: already refuses rather than silently ignoring when enriching itself is off, and Smart Search's
#: press says the same kind of sentence. The pane's own status for the first state is "On, but
#: every stash-box is turned off.", so the refusal names the same state in the same words. The
#: second covers a box named by the press and the one the setting chooses alike, since either way
#: it is the box this press would have asked. Chosen by `StashBoxService.cannot_ask`, and only there.
EVERY_BOX_OFF = "Every stash-box is turned off. Turn one on under Stash-boxes."
#: What a press says when enriching itself (`SCAN_KEY`) is turned off: the Tasks pane's Run now and
#: the Enrich press on files, folders and the whole library alike. One sentence for one state, and
#: it names where to turn it on.
ENRICHING_OFF = "Enriching with stash-boxes is turned off. Turn it on under Stash-boxes."
CHOSEN_BOX_OFF = (
    "The stash-box this would ask is turned off. Turn it on, or choose another, under Stash-boxes."
)


async def box_for(settings: SettingsSeam, named: str | None) -> str:
    """Which box a PRESS asks, as the per-file and per-subject jobs carry it: "" is every box.

    Three answers, and this is the one place they are told apart, for all three routes that queue
    a question (the file scan, the enrichment of people, sites and tags, and the enrichment a
    confirmation queues for what it named):

    - a box's own word asks that box and no other;
    - `EVERY_BOX` asks every switched-on box, whatever the setting says: the flyout's row;
    - nothing asks what `AUTO_BOX_KEY` names, which is "whatever is set up", the same rule the
      whole-library sweep follows, so one press and another cannot disagree.

    Resolved ONCE, at the route, and carried: a job reads the answer rather than the setting, so a
    setting changed while forty questions are queued does not split one press across two answers.
    """
    word = str(named or "").strip().lower()
    if word == EVERY_BOX:
        return ""
    if word:
        return word
    return await auto_box(settings) or ""


#: How far apart two lengths may be and still be the same release, in seconds.
#:
#: The cheapest disambiguator there is: a fingerprint question carries no duration, so a
#: perceptual match against a different cut of the same shoot comes back looking identical. Sift
#: grades by length itself (`service.grade_of`): outside this window a match is unsure, and a
#: match is certain on its picture only well inside it.
DURATION_KEY = "stash_boxes.duration_tolerance_s"
DURATION_DEFAULT_S = 10

#: The three rules, and what each is called on screen.
STRATEGIES = tuple(one.value for one in Strategy)
STRATEGY_LABELS = (
    "Leave alone",
    "Fill in what is missing",
    "Replace what is there",
)

#: Which subjects have per-field rules. A collection and a photo set are not here because no
#: stash-box Sift talks to has anything to say about either.
ENRICHED: tuple[Subject, ...] = (Subject.PERSON, Subject.SITE, Subject.TAG, Subject.ASSET)

#: What each subject is called in a settings label, in the singular.
_CALLED = {
    Subject.PERSON: "a person",
    Subject.SITE: "a Site",
    Subject.TAG: "a tag",
    Subject.ASSET: "a file",
}


def _switches() -> None:
    register_setting(
        key=SCAN_KEY,
        scope="app",
        default=False,
        section=SECTION,
        label="Enrich your library with stash-boxes",
        disclosure=(
            "A stash-box is a shared database of details about adult videos and the people in them. "
            "Sift sends each file's fingerprint and adds the details of any match to your library. "
            "Your files are never sent."
        ),
        help=(
            "Sift looks up your files on the stash-boxes you add, using your API key for each, and "
            "fills in their details."
        ),
        # Not asked at first run: yes alone does nothing, because a stash-box needs an address and
        # a key. Nothing here runs until a box is added, which is the deliberate act; the pane says
        # what leaves the machine before anything does.
    )
    # Enriching on a schedule is the enrichment task's When (`tasks.enrichment.when`). The key stays
    # as the name the sweep asks by; the composition root retires it.
    register_setting(
        key=AUTO_APPLY_KEY,
        scope="app",
        default=True,
        section=SECTION,
        label="Confirm exact matches automatically",
        disclosure=(
            "Running Auto-enrich yourself always confirms exact matches, because you asked for it. "
            "This decides only for lookups Sift starts by itself, such as for new files. Other "
            "matches wait in Organize either way."
        ),
        help=(
            "When an automatic lookup finds an exact match, Sift adds the details right away. "
            "Other matches wait in Organize."
        ),
    )
    register_setting(
        key=SHOW_EVERY_FIELD_KEY,
        # Per user: it stores nothing, requests nothing and costs the machine nothing, like the theme.
        scope="user",
        # On unless somebody turned it off: a record that hides fields reads as one missing them.
        # A stored value stands; only a value never stored follows the default.
        default=True,
        # Appearance, not here: this decides how a record is drawn and nothing else, so it belongs
        # with the other choices about what is on screen.
        section="Appearance",
        label="Show every field on a record",
        # The browser acts on this one: it decides which rows a record draws, and nothing on the
        # server reads it. What is STORED never changes, so it is safe to turn on and off again.
        read_by=ReadBy.CLIENT,
        disclosure=(
            "The extra fields are ones only a stash-box fills in, like eye color and height. "
            "Nothing is saved or deleted either way."
        ),
        help="When off, a record shows only its main fields.",
        default_since="0.1.218",
    )
    register_setting(
        key=AUTO_BOX_KEY,
        scope="app",
        default="",
        section=SECTION,
        choices=_AUTO_BOX_WORDS,
        choice_labels=_AUTO_BOX_LABELS,
        label="Auto-enrich using",
        disclosure=(
            "Every stash-box you add stays on, and you can still search any of them yourself."
        ),
        help=(
            "The stash-box Sift's automatic lookups use, and the one Auto-enrich uses when you don't "
            "choose one."
        ),
    )
    register_setting(
        key=DURATION_KEY,
        scope="app",
        default=DURATION_DEFAULT_S,
        section=SECTION,
        label="Allow lengths to differ by",
        minimum=0,
        maximum=600,
        unit="sec",
        disclosure=(
            "Sift ignores a match whose length differs by more than this, so a different cut of "
            "the same video isn't taken for yours."
        ),
        help="Two copies of the same video run for about the same time.",
    )


def _rules() -> None:
    """One rule per field a stash-box can fill in, from the registry that declares the fields."""
    for subject in ENRICHED:
        for one in fields_of(subject):
            if not one.imported:
                continue
            register_setting(
                key=strategy_key(subject, one.key),
                scope="app",
                default=DEFAULT_STRATEGY.value,
                section=SECTION,
                # The FIELD's own name and nothing else.
                #
                # Adding the subject (`f"{one.label} on {_CALLED[subject]}"`) would produce "Tags
                # on a person", "Shot on on a file" and "Who is in this on a file": a label whose
                # second half repeats the heading directly above it, and which reads as broken
                # English on any field whose own name already ends in a preposition. The subject
                # is the group heading, so the label says the one thing the heading does not.
                label=one.label,
                choices=STRATEGIES,
                choice_labels=STRATEGY_LABELS,
                # One short line, and the screen does not draw it.
                #
                # `SharedQuestion` carries the explanation once for all forty of these, and the rows
                # inside it are drawn with `showHelp={false}`. What is left here is what an API
                # reader and a settings search need: which subject this rule is about.
                help=f"What Sift does when a stash-box has this for {_CALLED[subject]}.",
            )


_switches()
_invent_switches()
_rules()
